[general]
  splash = false
  tick_rate = 250
  color = "gray"
  style = "plain"
  file_explorer = "xplr"
  detail_level = "minimum"
  # key_bindings = [
  #   { keys = [ "?" ], command = ":help" },
  #   { keys = [ "o" ], command = ":options" },
  #   { keys = [ "n" ], command = ":normal" },
  #   { keys = [ "v" ], command = ":visual" },
  #   { keys = [ "c" ], command = ":copy" },
  #   { keys = [ "p", "C-v" ], command = ":paste" },
  #   { keys = [ "x" ], command = ":export" },
  #   { keys = [ "s" ], command = ":set prompt :sign" },
  #   { keys = [ "e" ], command = ":set prompt :edit" },
  #   { keys = [ "i" ], command = ":set prompt :import"},
  #   { keys = [ "f" ], command = ":set prompt :receive" },
  #   { keys = [ "u" ], command = ":set prompt :send" },
  #   { keys = [ "g" ], command = ":generate" },
  #   { keys = [ "d", "backspace" ], command = ":delete" },
  #   { keys = [ "C-r" ], command = ":refresh" },
  # ]

[gpg]
  armor = false
  # homedir = "~/.gnupg"
  # outdir = "~/.gnupg/out"
  # outfile = "{type}_{query}.{ext}"
  # default_key = "0xA1B2C3XY"
